config/routes.rb
Rails.application.routes.draw do
  resources :posts
 resources :entries
 mount Sidekiq::Web => '/sidekiq' # TODO: block access to sidekiq only to the super admin
 devise_for :users, controllers: { registrations: "users/registrations",  sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 get 'theatre/:id/shows',to: 'homes#theatre_wise_movies',as: 'theatre_wise_movies'
 get 'movie/:id/theatres', to: 'homes#movie_in_theatres' ,as: 'movie_in_theatres'
 get 'all_theatres', to: 'homes#all_theatres'
 get 'thank_you', to: 'homes#thank_you'
 get 'reports', to: 'reports#index'
 root 'entries#index'

 resources :theatres do
  resources :screens do
    resources :seats
  end
end

resources :movies do
  resources :comments do
    member do
      get :approve
      get :reject
    end
  end
  resources :shows do
    get 'send_feedback_email'
    resources :bookings
  end
end

resources :bookings do
  resources :tickets
end



end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps

  #attributes
  field :rating, type: Integer
  field :review, type: String
  field :status, type: String, default: "pending"
  field :approved_by, type: String

  #associations
  belongs_to :user
  belongs_to :movie

  #validations
  validates :rating, :review, :status, :approved_by, presence: true
  validates_numericality_of :rating, length: { minimum: 0, maximum: 10 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	load_and_authorize_resource

	before_action :load_authorize_parent
	before_action :authenticate_user_from_token!

	def index
		@comments = @movie.comments.paginate(:per_page => 10, :page => params[:page])
	end
	def show

	end
	def new
		@user_token = params[:user_token]
	end

	def create
		@comment = @movie.comments.new(comment_params)
		@comment.user_id = current_user.id
		respond_to do |format|
			if @comment.save
				flash[:notice] = "Comment created successfully"
				format.html { redirect_to params[:user_token].presence ? thank_you_path : movie_comments_path(@movie) }
				format.json { render :show, status: :created, location: @comment }
			else
				format.html { render :new }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end
	def edit
	end

	def approve
		@comment.status = 'approve'
		@comment.approved_by=current_user.first_name
		respond_to do |format|
			if @comment.update_attributes
				format.html { redirect_to movie_comments_path(@movie)}
				format.json { render :show, status: :ok, location: @comment }
			end
		end
	end
	def reject
		@comment.status = 'reject'
		@comment.approved_by=current_user.first_name
		respond_to do |format|
			if @comment.update_attributes
				format.html { redirect_to movie_comments_path(@movie)}
				format.json { render :show, status: :ok, location: @comment }
			end
		end
	end

	def update

		respond_to do |format|
			if @comment.update(comment_params)
				flash[:notice] = "Comment updated successfully"
				format.html { redirect_to movie_comments_path(@movie), notice: 'Comment was successfully updated.' }
				format.json { render :show, status: :ok, location: @comment }
			else
				format.html { render :edit }
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@comment.destroy
		respond_to do |format|
			flash[:notice] = "Comment destroyed successfully"
			format.html { redirect_to movie_comments_path(@movie) }
			format.json { head :no_content }
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:rating, :review, :movie_id,:status)
	end

	def load_authorize_parent
		if params[:movie_id].present?
			@movie = Movie.find(params[:movie_id])
		end
	end
end

app/views/comments/_form.html.erb
<%= form_for [@movie,@comment] do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%@star = @comment.rating.present? ? @comment.rating : 0%>
<h3>Movie Name:<%= @movie.name %></h3>
<div class="form-group">
  <%= f.label :rating %><br>
  <%= f.hidden_field :rating, id: "rating_simple",:required => true , class: "form-control",:readonly=>true %>
  <span>Star:<span class="starcount"><%=@star%></span></span>
</div>
<div class="form-group">
  <%= f.label :review %><br>
  <%= f.text_area :review , class: "form-control" , :required => true%>
  <%= hidden_field_tag :user_token,@user_token %>
</div>
<div class="form-group">
  <%= f.submit class: "btn btn-default btn-action" %>
</div>
<% end %>

<script language="javascript" type="text/javascript">
 var count=<%=@star%>
 $(function() {
  $("#rating_simple").webwidget_rating_simple({
    rating_star_length: '10',
    rating_initial_value:count,
    rating_function_name: '',
    directory: '/images/'
  });
});
</script>

app/views/comments/edit.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
	<%= render 'shared/breadcrumb' %>
  <div class="well">
    <%= render 'form' %>
    <%= link_to 'Back', movie_comments_path(@movie) %>
  </div>
</div>

app/views/comments/index.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
	<%= render 'shared/breadcrumb' %>
	<% if flash[:notice] %>
	<div class="alert alert-success">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= flash[:notice] %>
	</div>
	<% end %>
	<% if can? :create, Comment %>
	<%= link_to 'New comment', new_movie_comment_path %>
	<% end %>
	<div class="well">
		<h1>Listing comments</h1>
		<table id="datatable" class="table table-condensed">
			<thead>
				<tr>
					<th>Name</th>
					<th>MovieName</th>
					<th>Rating</th>
					<th>Review</th>
					<th>Status</th>
					<% if current_user.role == "admin"%>
					<th colspan =4>Action</th>
					<% end %>
				</tr>
			</thead>
			<tbody>
				<% @comments.each do |comment| %>
				<tr>
					<td><%= comment.user.first_name  if comment.user.present?%></td>
					<td><%= comment.movie.name %></td>
					<td><%= comment.rating %></td>
					<td><%= comment.review %></td>
					<td><%= comment.status %></td>
					<% if can? :manage, Comment %>
					<td><%= link_to 'Approved', approve_movie_comment_path(@movie,comment),class: "" ,title: "Approved" if comment.status=='pending' || comment.status=='reject' %></td>
					<td><%= link_to 'Reject', reject_movie_comment_path(@movie,comment),class: "" ,title: "Reject" if comment.status=='pending' || comment.status=='approve' %></td>
					<td><%= link_to '', edit_movie_comment_path(@movie,comment),class: "fa fa-pencil-square-o" ,title: "Edit" %></td>
					<td><%= link_to '',[@movie,comment], method: :delete, data: { confirm: 'Are you sure?' } ,class: "fa fa-times", title: "Delete" %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="digg_pagination">
			<%= will_paginate @comments, :container => false %>
		</div>
	</div>
</div>

app/views/comments/new.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
	<%= render 'shared/breadcrumb' %>
  <div class="well">
    <%= render 'form' %>
  </div>
</div>