config/routes.rb
Rails.application.routes.draw do
  resources :posts
 resources :entries
 mount Sidekiq::Web => '/sidekiq' # TODO: block access to sidekiq only to the super admin
 devise_for :users, controllers: { registrations: "users/registrations",  sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 get 'theatre/:id/shows',to: 'homes#theatre_wise_movies',as: 'theatre_wise_movies'
 get 'movie/:id/theatres', to: 'homes#movie_in_theatres' ,as: 'movie_in_theatres'
 get 'all_theatres', to: 'homes#all_theatres'
 get 'thank_you', to: 'homes#thank_you'
 get 'reports', to: 'reports#index'
 root 'entries#index'

 resources :theatres do
  resources :screens do
    resources :seats
  end
end

resources :movies do
  resources :comments do
    member do
      get :approve
      get :reject
    end
  end
  resources :shows do
    get 'send_feedback_email'
    resources :bookings
  end
end

resources :bookings do
  resources :tickets
end



end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    if params[:page].present?
      params[:page] = params[:page].to_i <= 0 ? 1 : params[:page]
    end
    @movies = Movie.search(params[:search]).paginate(:per_page => 10, :page => params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        flash[:notice] = "Movie created successfully"
        format.html { redirect_to @movie }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        flash[:notice] = "Movie updated successfully"
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      flash[:notice] = "Movie destroyed successfully"
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
  def movie_params
    params.require(:movie).permit(:name, :language, :genre, :duration, :movie_format, :trailer_url, :rating, :release_date)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<% if @movie.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

  <ul>
    <% @movie.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%@star=@movie.rating.present? ? @movie.rating : 0%>
<div class="form-group">
  <%= f.label :name %><br>
  <%= f.text_field :name, :required => true, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :language %><br>
  <%= f.select :language, LANGUAGE, {}, :required => true, class: "form-control", :selected => f.object.language %>
</div>
<div class="form-group">
  <%= f.label :genre %><br>
  <%= f.select :genre, GENRE, {}, :required => true, class: "form-control", :selected => f.object.genre %>
</div>

<div class="form-group">
  <%= f.label :duration %><br>
  <%= f.text_field :duration, :required => true, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :movie_format %><br>
  <%= f.select :movie_format, MOVIE_FORMAT, {}, :required => true, class: "form-control", :selected => f.object.movie_format %>
</div>
<div class="form-group">
  <%= f.label :trailer_url %><br>
  <%= f.text_field :trailer_url,:required => true , class: "form-control"  %>
</div>
<div class="form-group">
  <%= f.label :rating %><br>
  <%= f.hidden_field :rating, id: "rating_simple",:required => true , class: "form-control",:readonly=>true %>
  <span>Star:<span class="starcount"><%=@star%></span></span>
</div>

<div class="form-group">
  <%= f.label :release_date %><br>
  <%= f.date_field :release_date ,:required => true, class: "form-control"  %>
</div>
<div class="form-group">
  <%= f.submit class: "btn btn-default" %>
</div>
<% end %>

<script language="javascript" type="text/javascript">
 var count=<%=@star%>
  $(function() {
    $("#rating_simple").webwidget_rating_simple({
      rating_star_length: '10',
      rating_initial_value:count,
      rating_function_name: '',
      directory: '/images/'
    });
  });
</script>

app/views/movies/edit.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <div class="well">
    <%= render 'form' %>
    <%= link_to 'Show', @movie %> |
    <%= link_to 'Back', movies_path %>
  </div>
</div>

app/views/movies/index.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if can? :create, Movie %>
    <%= link_to 'New Movie', new_movie_path %>
  <% end %>
  <div class="well">
    <h1>Listing Movies</h1>
    <%= form_tag movies_path, :method => 'get', :id => "movies_search" do %>
    <p class="form-inline">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Language</th>
          <th>Genre</th>
          <th>Duration</th>
          <th>Movie format</th>
          <th>Trailer url</th>
          <th>Rating</th>
          <th>Release date</th>
          <% if current_user.role == "admin"%>
          <th>Comment</th>
          <th>Movies Shows</th>
          <th colspan =3>Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.name %></td>
          <td><%= movie.language %></td>
          <td><%= movie.genre %></td>
          <td><%= movie.duration %></td>
          <td><%= movie.movie_format %></td>
          <td><%= movie.trailer_url %></td>
          <td><%= movie.rating %></td>
          <td><%= movie.release_date %></td>
          <% if can? :manage, Movie %>
          <td><%= link_to 'Add Shows', movie_shows_path(movie) %></td>
          <td><%= link_to 'Comments', movie_comments_path(movie) %></td>
          <td><%= link_to '', movie,class: "fa fa-eye" ,title: "Show"%></td>
          <td><%= link_to '', edit_movie_path(movie),class: "fa fa-pencil-square-o" ,title: "Edit" %></td>
          <td><%= link_to '', movie, method: :delete, data: { confirm: 'Are you sure?' } ,class: "fa fa-times", title: "Delete" %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="digg_pagination">
      <%= will_paginate @movies, :container => false %>
    </div>
  </div>

app/views/movies/new.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <div class="well">
    <p class="lead">Add New Movie</p>
    <%= render 'form' %>
    <%= link_to 'Back', movies_path %>
  </div>
</div>

app/views/movies/show.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= flash[:notice] %>
  </div>
  <% end %>
  <%= render 'shared/breadcrumb' %>
  <div class="well">
    <p class="lead">
      <strong>Name:</strong>
      <%= @movie.name %>
    </p>

    <p class="lead">
      <strong>Language:</strong>
      <%= @movie.language %>
    </p>

    <p class="lead">
      <strong>Genre:</strong>
      <%= @movie.genre %>
    </p>

    <p class="lead">
      <strong>Duration:</strong>
      <%= @movie.duration %>
    </p>

    <p class="lead">
      <strong>Movie format:</strong>
      <%= @movie.movie_format %>
    </p>

    <p class="lead">
      <strong>Trailer url:</strong>
      <%= @movie.trailer_url %>
    </p>

    <p class="lead">
      <strong>Rating:</strong>
      <%= @movie.rating %>
    </p>

    <p class="lead">
      <strong>Release date:</strong>
      <%= @movie.release_date %>
    </p>
    <% if can? :manage, Movie %>
    <% if current_user.role == "admin" %>
    <%= link_to 'Edit', edit_movie_path(@movie) %> |
    <% end %>
    <%= link_to 'Back', movies_path %>|
    <% end %>

    <%= link_to 'Add Review', new_movie_comment_path(@movie) %>
  </div>
</div>