config/routes.rb
Rails.application.routes.draw do
  resources :posts
 resources :entries
 mount Sidekiq::Web => '/sidekiq' # TODO: block access to sidekiq only to the super admin
 devise_for :users, controllers: { registrations: "users/registrations",  sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 get 'theatre/:id/shows',to: 'homes#theatre_wise_movies',as: 'theatre_wise_movies'
 get 'movie/:id/theatres', to: 'homes#movie_in_theatres' ,as: 'movie_in_theatres'
 get 'all_theatres', to: 'homes#all_theatres'
 get 'thank_you', to: 'homes#thank_you'
 get 'reports', to: 'reports#index'
 root 'entries#index'

 resources :theatres do
  resources :screens do
    resources :seats
  end
end

resources :movies do
  resources :comments do
    member do
      get :approve
      get :reject
    end
  end
  resources :shows do
    get 'send_feedback_email'
    resources :bookings
  end
end

resources :bookings do
  resources :tickets
end



end

app/views/shared/_breadcrumb.html.erb
<ol class="breadcrumb">
	<li><%= link_to('Home', root_path) %></li>

	<% if @movie.present? %>
		<li><a href="<%= movies_path %>">Movies</a></li>

		<% if @movie.present? %>
		<% if @movie.new_record? %>
		<li class="active">New Movie</li>
		<% else %>
		<li><a href="<%= movie_shows_path(@movie) %>">Shows</a></li>
		<li class="active"><%= @movie.name %></li>
		<% end %>
	<% end %>
	<% else %>
		<%if @seats.present?%>
			<% if @theatre.present? %>
				<li><a href="<%= theatres_path %>">Theatre</a></li>
			<% end %>
			<% if @screen.present? %>
				<li><a href="<%= theatre_screens_path %>"><%=@screen.name%></a></li>
				<li class="active">Seats</li>
			<% end %>

		<%elsif @seat.present?%>

			<% if @theatre.present? %>
				<li><a href="<%= theatres_path %>">Theatre</a></li>
			<% end %>

			<% if @screen.present? %>
				<li><a href="<%= theatre_screens_path %>"><%=@screen.name%></a></li>
			<% end %>

				<% if @seat.new_record? %>
					<li class="active">New Seat</li>
				<% else %>
					<li><a href="<%= theatre_screen_seats_path %>">Seats</a></li>
					<li class="active"><%= @seat.row %></li>
				<% end %>

		<% else %>

			<% if @theatre.present? %>
				<li><a href="<%= theatres_path %>">Theatre</a></li>
			<% end %>
			<% if @theatre.present? %>
				<% if @theatre.new_record? %>
					<li class="active">New Theatre</li>
				<% else %>
					<li class="active"><%= @theatre.name %></li>
				<% end %>
			<% end %>
			<% if @screen.present? %>
				<% if @screen.new_record? %>
					<li class="active">New Screen</li>
				<% else %>
					<li class="active"><%= @screen.name %></li>
				<% end %>
			<% end %>

			<% if @screens.present? %>
			<li class="active">Screens</li>
			<%end%>
		<% end %>
	<% end %>
</ol>