config/routes.rb
Rails.application.routes.draw do
  resources :posts
 resources :entries
 mount Sidekiq::Web => '/sidekiq' # TODO: block access to sidekiq only to the super admin
 devise_for :users, controllers: { registrations: "users/registrations",  sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations" }
 get 'theatre/:id/shows',to: 'homes#theatre_wise_movies',as: 'theatre_wise_movies'
 get 'movie/:id/theatres', to: 'homes#movie_in_theatres' ,as: 'movie_in_theatres'
 get 'all_theatres', to: 'homes#all_theatres'
 get 'thank_you', to: 'homes#thank_you'
 get 'reports', to: 'reports#index'
 root 'entries#index'

 resources :theatres do
  resources :screens do
    resources :seats
  end
end

resources :movies do
  resources :comments do
    member do
      get :approve
      get :reject
    end
  end
  resources :shows do
    get 'send_feedback_email'
    resources :bookings
  end
end

resources :bookings do
  resources :tickets
end



end

app/models/show.rb
class Show
  include Mongoid::Document
  include Mongoid::Timestamps

  #attributes
  field :starttime, type: DateTime
  field :endtime, type: DateTime

  #associations
  belongs_to :screen
  belongs_to :movie
  belongs_to :theatre
  has_many :bookings
  has_many :tickets

  #validations
  validates :starttime, :endtime, presence: true
  validate :starttime_cannot_be_in_the_past, on: :create
  validate :check_for_existing?, on: :create

  def starttime_cannot_be_in_the_past
    if starttime.present? && starttime < DateTime.now
      errors.add(:starttime, "can't be in the past")
    end
  end

  private
  def check_for_existing?
    options = {}
    if self.movie_id.present?
      options['movie_id'] = self.movie_id
      if self.starttime.present?
        options['starttime'] = self.starttime
        if self.screen_id.present?
          options['screen_id'] = self.screen_id
          show = Show.where(options)
        end
      end
    end
    if show.count > 0
      self.errors.add :base, " Show already exists"
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	load_and_authorize_resource
	before_action :load_authorize_parent

	def index
		@shows = @movie.shows.paginate(:page=>params[:page],:per_page=>10)
	end

	def show
		@shows = @movie.includes(:shows).group_by {|show| show.theatre.name}
	end

	def new
	end

	def edit
	end

	def create
		@show = @movie.shows.new(show_params)
		@show.endtime = (@show.starttime.to_time + @movie.duration.hours).to_datetime
		respond_to do |format|
			if @show.save
				format.html { redirect_to movie_shows_path(@movie), notice: 'Show was successfully created.' }
				format.json { render :show, status: :created, location: @show }
			else
				format.html { render :new }
				format.json { render json: @show.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @show.update(show_params)
				format.html { redirect_to movie_shows_path(@movie), notice: 'Show was successfully updated.' }
				format.json { render :show, status: :ok, location: @show }
			else
				format.html { render :edit }
				format.json { render json: @show.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@show.destroy
		respond_to do |format|
			format.html { redirect_to movie_shows_path(@movie), notice: 'Show was successfully destroyed.' }
			format.json { head :no_content }
		end
	end
	def send_feedback_email
		respond_to do |format|
			show = Show.find(params[:show_id])
			show.bookings.each do |booking|
				MovieFeedbackJob.perform_later(booking.id.to_s)
			end
			format.html { redirect_to movie_shows_path(@movie), notice: 'Email Send .' }
			format.json { head :no_content }
		end
	end

	private

	def show_params
		params.require(:show).permit(:starttime, :endtime, :screen_id,:theatre_id)
	end

	def load_authorize_parent
		if params[:movie_id].present?
			@movie = Movie.find(params[:movie_id])
		end
	end

end

app/views/shows/_form.html.erb
<%= form_for [@movie,@show] do |f| %>
<% if @show.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>
  <ul>
    <% @show.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">

</div>
<div class="field">
  <%= f.label :theatre_id %><br />
  <%= f.collection_select :theatre_id, Theatre.order_by(:name=>'ASC'), :id, :name, include_blank: true %>
</div>
<div class="field">
  <%= f.label :screen_id, "Screen Name" %><br />
  <%= f.grouped_collection_select :screen_id, Theatre.order_by(:name=>'ASC'), :screens, :name, :id, :name, include_blank: true %>
</div>


<div class="form-group">
  <%= f.label :starttime, class: "control-label" %>
  <%= f.datetime_local_field :starttime, class: "", required: "required"  %>
</div>
<div class="form-group">
  <%= f.submit class: "btn btn-default" %>
</div>
<% end %>

<script type="text/javascript">
$(document).ready(function(){
   screens = $('#show_screen_id').html()
  $('#show_theatre_id').change(function(){
    Theatre = $('#show_theatre_id :selected').text()
    options = $(screens).filter("optgroup[label='"+Theatre+"']").html()
    if (options) {
    $('#show_screen_id').html(options)
    $('#show_screen_id').parent().show()
    }
    else{
      $('#show_screen_id').empty()
     $('#show_screen_id').parent().hide()
   }
  })
});
</script>

app/views/shows/edit.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <div class="well">
    <%= render 'form' %>
    <%= link_to 'Show', movie_show_path(@movie,@show) %> |
    <%= link_to 'Back', movie_shows_path(@movie) %>
  </div>
</div>

app/views/shows/index.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <% if can? :manage, Show %>
  <%= link_to 'New Show', new_movie_show_path(@movie) %>
  <% end %>
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= flash[:notice] %>
  </div>
  <% end %>
  <div class="well">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Screen</th>
          <th>Theater</th>
          <% if can? :manage, Show %>
          <th>Send FeedBack Email</th>
          <th colspan =3>Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @shows.each do |show| %>
        <tr>
          <td><%= show.starttime.strftime(" %d/%m/%Y time- %I:%M%p") %></td>
          <td><%= show.endtime.strftime("%d/%m/%Y time- %I:%M%p") %></td>
          <td><%= show.screen.name if show.screen? %></td>
          <td><%= show.screen.theatre.name if show.screen.theatre? %></td>
          <% if can? :manage, Show %>
           <td><%= link_to 'FeedBack Email', movie_show_send_feedback_email_path(@movie,show),class: "" ,title: "FeedBack Email" %></td>
          <td><%= link_to '', movie_show_path(@movie,show),class: "fa fa-eye" ,title: "Show" %></td>
          <td><%= link_to '', edit_movie_show_path(@movie,show),class: "fa fa-pencil-square-o" ,title: "Edit"%></td>
          <td><%= link_to '',[@movie,show], method: :delete, data: { confirm: 'Are you sure?' },class: "fa fa-times", title: "Delete" %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="digg_pagination">
      <%= will_paginate @shows, :container => false %>
    </div>
  </div>
</div>

app/views/shows/new.html.erb
<%= render template: "layouts/headbar" %>
<div class="container">
  <%= render 'shared/breadcrumb' %>
  <div class="well">
    <%= render 'form' %>
    <%= link_to 'Back', movie_shows_path(@movie) %>
  </div>
</div>